window.esdocSearchIndex = [
  [
    "@alexvv13/tpapi/lib/parks/bellewaerde/bellewaerde.js~bellewaerde",
    "class/lib/parks/bellewaerde/bellewaerde.js~Bellewaerde.html",
    "<span>Bellewaerde</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/bellewaerde/bellewaerde.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/cdaparks/cdabase.js~cdabase",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html",
    "<span>CDABase</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/cdaparks/cdabase.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/cache/cachebase.js~cachebase",
    "class/lib/cache/cacheBase.js~CacheBase.html",
    "<span>CacheBase</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/cache/cacheBase.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/cache/cachelevel.js~cachelevel",
    "class/lib/cache/cacheLevel.js~CacheLevel.html",
    "<span>CacheLevel</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/cache/cacheLevel.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/cache/cachememory.js~cachememory",
    "class/lib/cache/cacheMemory.js~CacheMemory.html",
    "<span>CacheMemory</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/cache/cacheMemory.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/configbase.js~configbase",
    "class/lib/configBase.js~ConfigBase.html",
    "<span>ConfigBase</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/configBase.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/efteling/efteling.js~efteling",
    "class/lib/parks/efteling/efteling.js~Efteling.html",
    "<span>Efteling</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/efteling/efteling.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/entity.js~entity",
    "class/lib/parks/entity.js~Entity.html",
    "<span>Entity</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/entity.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/europapark/europapark.js~europapark",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html",
    "<span>EuropaPark</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/europapark/europapark.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/europapark/europaparkbase.js~europaparkbase",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html",
    "<span>EuropaParkBase</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/europapark/europaparkbase.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/location.js~location",
    "class/lib/parks/location.js~Location.html",
    "<span>Location</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/location.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/park.js~park",
    "class/lib/parks/park.js~Park.html",
    "<span>Park</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/park.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/phantasialand/phantasialand.js~phantasialand",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html",
    "<span>Phantasialand</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/phantasialand/phantasialand.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/europapark/rulantica.js~rulantica",
    "class/lib/parks/europapark/rulantica.js~Rulantica.html",
    "<span>Rulantica</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/europapark/rulantica.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/cache/scopedcache.js~scopedcache",
    "class/lib/cache/scopedCache.js~ScopedCache.html",
    "<span>ScopedCache</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/cache/scopedCache.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/toverland/toverland.js~toverland",
    "class/lib/parks/toverland/toverland.js~Toverland.html",
    "<span>Toverland</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/toverland/toverland.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/walibi/walibibelgium.js~walibibelgium",
    "class/lib/parks/walibi/walibibelgium.js~WalibiBelgium.html",
    "<span>WalibiBelgium</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/walibi/walibibelgium.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/walibi/walibiholland.js~walibiholland",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html",
    "<span>WalibiHolland</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/walibi/walibiholland.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/walibi/walibira.js~walibira",
    "class/lib/parks/walibi/walibira.js~WalibiRA.html",
    "<span>WalibiRA</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/walibi/walibira.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/europapark/yullbe.js~yullbe",
    "class/lib/parks/europapark/yullbe.js~Yullbe.html",
    "<span>Yullbe</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/europapark/yullbe.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/tags.js~entitycategory",
    "variable/index.html#static-variable-entityCategory",
    "<span>entityCategory</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/tags.js</span>",
    "variable"
  ],
  [
    "@alexvv13/tpapi/lib/parks/tags.js~entitytags",
    "variable/index.html#static-variable-entityTags",
    "<span>entityTags</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/tags.js</span>",
    "variable"
  ],
  [
    "@alexvv13/tpapi/lib/cache.js~getcache",
    "function/index.html#static-function-getCache",
    "<span>getCache</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/cache.js</span>",
    "function"
  ],
  [
    "@alexvv13/tpapi/lib/configbase.js~parseconfig",
    "function/index.html#static-function-parseConfig",
    "<span>parseConfig</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/configBase.js</span>",
    "function"
  ],
  [
    "@alexvv13/tpapi/lib/parks/types.js~queueentity",
    "variable/index.html#static-variable-queueEntity",
    "<span>queueEntity</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/types.js</span>",
    "variable"
  ],
  [
    "@alexvv13/tpapi/lib/reusepromises.js~reusepromise",
    "function/index.html#static-function-reusePromise",
    "<span>reusePromise</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/reusePromises.js</span>",
    "function"
  ],
  [
    "@alexvv13/tpapi/lib/reusepromises.js~reusepromiseforever",
    "function/index.html#static-function-reusePromiseForever",
    "<span>reusePromiseForever</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/reusePromises.js</span>",
    "function"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/cache.js",
    "file/lib/cache.js.html",
    "lib/cache.js",
    "file"
  ],
  [
    "lib/cache/cachebase.js",
    "file/lib/cache/cacheBase.js.html",
    "lib/cache/cacheBase.js",
    "file"
  ],
  [
    "lib/cache/cachebase.js~cachebase#_del",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-_del",
    "lib/cache/cacheBase.js~CacheBase#_del",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#_get",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-_get",
    "lib/cache/cacheBase.js~CacheBase#_get",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#_getkeys",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-_getKeys",
    "lib/cache/cacheBase.js~CacheBase#_getKeys",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#_set",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-_set",
    "lib/cache/cacheBase.js~CacheBase#_set",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#constructor",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-constructor-constructor",
    "lib/cache/cacheBase.js~CacheBase#constructor",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#failedcachewraps",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-member-failedCacheWraps",
    "lib/cache/cacheBase.js~CacheBase#failedCacheWraps",
    "member"
  ],
  [
    "lib/cache/cachebase.js~cachebase#get",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-get",
    "lib/cache/cacheBase.js~CacheBase#get",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#getkeys",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-getKeys",
    "lib/cache/cacheBase.js~CacheBase#getKeys",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#memcache",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-member-memCache",
    "lib/cache/cacheBase.js~CacheBase#memCache",
    "member"
  ],
  [
    "lib/cache/cachebase.js~cachebase#memorylayerenabled",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-member-memoryLayerEnabled",
    "lib/cache/cacheBase.js~CacheBase#memoryLayerEnabled",
    "member"
  ],
  [
    "lib/cache/cachebase.js~cachebase#pendingcachewraps",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-member-pendingCacheWraps",
    "lib/cache/cacheBase.js~CacheBase#pendingCacheWraps",
    "member"
  ],
  [
    "lib/cache/cachebase.js~cachebase#set",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-set",
    "lib/cache/cacheBase.js~CacheBase#set",
    "method"
  ],
  [
    "lib/cache/cachebase.js~cachebase#wrap",
    "class/lib/cache/cacheBase.js~CacheBase.html#instance-method-wrap",
    "lib/cache/cacheBase.js~CacheBase#wrap",
    "method"
  ],
  [
    "lib/cache/cachelevel.js",
    "file/lib/cache/cacheLevel.js.html",
    "lib/cache/cacheLevel.js",
    "file"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#_del",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-method-_del",
    "lib/cache/cacheLevel.js~CacheLevel#_del",
    "method"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#_get",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-method-_get",
    "lib/cache/cacheLevel.js~CacheLevel#_get",
    "method"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#_getkeys",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-method-_getKeys",
    "lib/cache/cacheLevel.js~CacheLevel#_getKeys",
    "method"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#_set",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-method-_set",
    "lib/cache/cacheLevel.js~CacheLevel#_set",
    "method"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#constructor",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-constructor-constructor",
    "lib/cache/cacheLevel.js~CacheLevel#constructor",
    "method"
  ],
  [
    "lib/cache/cachelevel.js~cachelevel#db",
    "class/lib/cache/cacheLevel.js~CacheLevel.html#instance-member-db",
    "lib/cache/cacheLevel.js~CacheLevel#db",
    "member"
  ],
  [
    "lib/cache/cachememory.js",
    "file/lib/cache/cacheMemory.js.html",
    "lib/cache/cacheMemory.js",
    "file"
  ],
  [
    "lib/cache/cachememory.js~cachememory#_del",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-method-_del",
    "lib/cache/cacheMemory.js~CacheMemory#_del",
    "method"
  ],
  [
    "lib/cache/cachememory.js~cachememory#_get",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-method-_get",
    "lib/cache/cacheMemory.js~CacheMemory#_get",
    "method"
  ],
  [
    "lib/cache/cachememory.js~cachememory#_getkeys",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-method-_getKeys",
    "lib/cache/cacheMemory.js~CacheMemory#_getKeys",
    "method"
  ],
  [
    "lib/cache/cachememory.js~cachememory#_set",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-method-_set",
    "lib/cache/cacheMemory.js~CacheMemory#_set",
    "method"
  ],
  [
    "lib/cache/cachememory.js~cachememory#cache",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-member-cache",
    "lib/cache/cacheMemory.js~CacheMemory#cache",
    "member"
  ],
  [
    "lib/cache/cachememory.js~cachememory#constructor",
    "class/lib/cache/cacheMemory.js~CacheMemory.html#instance-constructor-constructor",
    "lib/cache/cacheMemory.js~CacheMemory#constructor",
    "method"
  ],
  [
    "lib/cache/scopedcache.js",
    "file/lib/cache/scopedCache.js.html",
    "lib/cache/scopedCache.js",
    "file"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#_initcache",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-_initCache",
    "lib/cache/scopedCache.js~ScopedCache#_initCache",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#_initcachepromise",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-member-_initCachePromise",
    "lib/cache/scopedCache.js~ScopedCache#_initCachePromise",
    "member"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#cache",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-member-cache",
    "lib/cache/scopedCache.js~ScopedCache#cache",
    "member"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#constructor",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-constructor-constructor",
    "lib/cache/scopedCache.js~ScopedCache#constructor",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#generatescopedkey",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-generateScopedKey",
    "lib/cache/scopedCache.js~ScopedCache#generateScopedKey",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#get",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-get",
    "lib/cache/scopedCache.js~ScopedCache#get",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#getglobal",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-getGlobal",
    "lib/cache/scopedCache.js~ScopedCache#getGlobal",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#initcache",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-initCache",
    "lib/cache/scopedCache.js~ScopedCache#initCache",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#prefix",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-member-prefix",
    "lib/cache/scopedCache.js~ScopedCache#prefix",
    "member"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#set",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-set",
    "lib/cache/scopedCache.js~ScopedCache#set",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#setglobal",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-setGlobal",
    "lib/cache/scopedCache.js~ScopedCache#setGlobal",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#version",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-member-version",
    "lib/cache/scopedCache.js~ScopedCache#version",
    "member"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#wrap",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-wrap",
    "lib/cache/scopedCache.js~ScopedCache#wrap",
    "method"
  ],
  [
    "lib/cache/scopedcache.js~scopedcache#wrapglobal",
    "class/lib/cache/scopedCache.js~ScopedCache.html#instance-method-wrapGlobal",
    "lib/cache/scopedCache.js~ScopedCache#wrapGlobal",
    "method"
  ],
  [
    "lib/configbase.js",
    "file/lib/configBase.js.html",
    "lib/configBase.js",
    "file"
  ],
  [
    "lib/configbase.js~configbase#config",
    "class/lib/configBase.js~ConfigBase.html#instance-member-config",
    "lib/configBase.js~ConfigBase#config",
    "member"
  ],
  [
    "lib/configbase.js~configbase#constructor",
    "class/lib/configBase.js~ConfigBase.html#instance-constructor-constructor",
    "lib/configBase.js~ConfigBase#constructor",
    "method"
  ],
  [
    "lib/index.js",
    "file/lib/index.js.html",
    "lib/index.js",
    "file"
  ],
  [
    "lib/parks/bellewaerde/bellewaerde.js",
    "file/lib/parks/bellewaerde/bellewaerde.js.html",
    "lib/parks/bellewaerde/bellewaerde.js",
    "file"
  ],
  [
    "lib/parks/bellewaerde/bellewaerde.js~bellewaerde#constructor",
    "class/lib/parks/bellewaerde/bellewaerde.js~Bellewaerde.html#instance-constructor-constructor",
    "lib/parks/bellewaerde/bellewaerde.js~Bellewaerde#constructor",
    "method"
  ],
  [
    "lib/parks/cdaparks/cdabase.js",
    "file/lib/parks/cdaparks/cdabase.js.html",
    "lib/parks/cdaparks/cdabase.js",
    "file"
  ],
  [
    "lib/parks/cdaparks/cdabase.js~cdabase#buildmerchandisepoi",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html#instance-method-buildMerchandisePOI",
    "lib/parks/cdaparks/cdabase.js~CDABase#buildMerchandisePOI",
    "method"
  ],
  [
    "lib/parks/cdaparks/cdabase.js~cdabase#buildrestaurantpoi",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html#instance-method-buildRestaurantPOI",
    "lib/parks/cdaparks/cdabase.js~CDABase#buildRestaurantPOI",
    "method"
  ],
  [
    "lib/parks/cdaparks/cdabase.js~cdabase#buildridepoi",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html#instance-method-buildRidePOI",
    "lib/parks/cdaparks/cdabase.js~CDABase#buildRidePOI",
    "method"
  ],
  [
    "lib/parks/cdaparks/cdabase.js~cdabase#buildservicepoi",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html#instance-method-buildServicePOI",
    "lib/parks/cdaparks/cdabase.js~CDABase#buildServicePOI",
    "method"
  ],
  [
    "lib/parks/cdaparks/cdabase.js~cdabase#buildshowpoi",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html#instance-method-buildShowPOI",
    "lib/parks/cdaparks/cdabase.js~CDABase#buildShowPOI",
    "method"
  ],
  [
    "lib/parks/cdaparks/cdabase.js~cdabase#buildwcpoi",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html#instance-method-buildWCPOI",
    "lib/parks/cdaparks/cdabase.js~CDABase#buildWCPOI",
    "method"
  ],
  [
    "lib/parks/cdaparks/cdabase.js~cdabase#constructor",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html#instance-constructor-constructor",
    "lib/parks/cdaparks/cdabase.js~CDABase#constructor",
    "method"
  ],
  [
    "lib/parks/cdaparks/cdabase.js~cdabase#getophours",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html#instance-method-getOpHours",
    "lib/parks/cdaparks/cdabase.js~CDABase#getOpHours",
    "method"
  ],
  [
    "lib/parks/cdaparks/cdabase.js~cdabase#getpois",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html#instance-method-getPOIS",
    "lib/parks/cdaparks/cdabase.js~CDABase#getPOIS",
    "method"
  ],
  [
    "lib/parks/cdaparks/cdabase.js~cdabase#getqueue",
    "class/lib/parks/cdaparks/cdabase.js~CDABase.html#instance-method-getQueue",
    "lib/parks/cdaparks/cdabase.js~CDABase#getQueue",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js",
    "file/lib/parks/efteling/efteling.js.html",
    "lib/parks/efteling/efteling.js",
    "file"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#buildfairytalepoi",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-buildFairytalePOI",
    "lib/parks/efteling/efteling.js~Efteling#buildFairytalePOI",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#buildmerchandisepoi",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-buildMerchandisePOI",
    "lib/parks/efteling/efteling.js~Efteling#buildMerchandisePOI",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#buildrestaurantpoi",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-buildRestaurantPOI",
    "lib/parks/efteling/efteling.js~Efteling#buildRestaurantPOI",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#buildridepoi",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-buildRidePOI",
    "lib/parks/efteling/efteling.js~Efteling#buildRidePOI",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#buildshowpoi",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-buildShowPOI",
    "lib/parks/efteling/efteling.js~Efteling#buildShowPOI",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#constructor",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-constructor-constructor",
    "lib/parks/efteling/efteling.js~Efteling#constructor",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getophours",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getOpHours",
    "lib/parks/efteling/efteling.js~Efteling#getOpHours",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getpois",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getPOIS",
    "lib/parks/efteling/efteling.js~Efteling#getPOIS",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getqueue",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getQueue",
    "lib/parks/efteling/efteling.js~Efteling#getQueue",
    "method"
  ],
  [
    "lib/parks/entity.js",
    "file/lib/parks/entity.js.html",
    "lib/parks/entity.js",
    "file"
  ],
  [
    "lib/parks/entity.js~entity#fastpass",
    "class/lib/parks/entity.js~Entity.html#instance-get-FastPass",
    "lib/parks/entity.js~Entity#FastPass",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#fastpassreturntimes",
    "class/lib/parks/entity.js~Entity.html#instance-get-FastPassReturnTimes",
    "lib/parks/entity.js~Entity#FastPassReturnTimes",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#langoptions",
    "class/lib/parks/entity.js~Entity.html#instance-get-LangOptions",
    "lib/parks/entity.js~Entity#LangOptions",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#locationstring",
    "class/lib/parks/entity.js~Entity.html#instance-get-LocationString",
    "lib/parks/entity.js~Entity#LocationString",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#name",
    "class/lib/parks/entity.js~Entity.html#instance-get-Name",
    "lib/parks/entity.js~Entity#Name",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#now",
    "class/lib/parks/entity.js~Entity.html#instance-get-Now",
    "lib/parks/entity.js~Entity#Now",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#supportsopeningtimes",
    "class/lib/parks/entity.js~Entity.html#instance-get-SupportsOpeningTimes",
    "lib/parks/entity.js~Entity#SupportsOpeningTimes",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#supportsrideschedules",
    "class/lib/parks/entity.js~Entity.html#instance-get-SupportsRideSchedules",
    "lib/parks/entity.js~Entity#SupportsRideSchedules",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#supportswaittimes",
    "class/lib/parks/entity.js~Entity.html#instance-get-SupportsWaitTimes",
    "lib/parks/entity.js~Entity#SupportsWaitTimes",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#timezone",
    "class/lib/parks/entity.js~Entity.html#instance-get-Timezone",
    "lib/parks/entity.js~Entity#Timezone",
    "member"
  ],
  [
    "lib/parks/entity.js~entity#constructor",
    "class/lib/parks/entity.js~Entity.html#instance-constructor-constructor",
    "lib/parks/entity.js~Entity#constructor",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#gettimenow",
    "class/lib/parks/entity.js~Entity.html#instance-method-getTimeNow",
    "lib/parks/entity.js~Entity#getTimeNow",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#gettimenowmoment",
    "class/lib/parks/entity.js~Entity.html#instance-method-getTimeNowMoment",
    "lib/parks/entity.js~Entity#getTimeNowMoment",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#getuniqueid",
    "class/lib/parks/entity.js~Entity.html#instance-method-getUniqueID",
    "lib/parks/entity.js~Entity#getUniqueID",
    "method"
  ],
  [
    "lib/parks/entity.js~entity#log",
    "class/lib/parks/entity.js~Entity.html#instance-method-log",
    "lib/parks/entity.js~Entity#log",
    "method"
  ],
  [
    "lib/parks/europapark/europapark.js",
    "file/lib/parks/europapark/europapark.js.html",
    "lib/parks/europapark/europapark.js",
    "file"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#constructor",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-constructor-constructor",
    "lib/parks/europapark/europapark.js~EuropaPark#constructor",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js",
    "file/lib/parks/europapark/europaparkbase.js.html",
    "lib/parks/europapark/europaparkbase.js",
    "file"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#bf",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-member-bf",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#bf",
    "member"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#buildhours",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-buildHours",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#buildHours",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#buildmerchandisepoi",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-buildMerchandisePOI",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#buildMerchandisePOI",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#buildrestaurantpoi",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-buildRestaurantPOI",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#buildRestaurantPOI",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#buildridepoi",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-buildRidePOI",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#buildRidePOI",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#buildservicepoi",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-buildServicePOI",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#buildServicePOI",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#buildstaticpoi",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-buildStaticPOI",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#buildStaticPOI",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#constructor",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-constructor-constructor",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#constructor",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#fetchhours",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-fetchHours",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#fetchHours",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#getconfig",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-getConfig",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#getConfig",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#getfirebaseid",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-getFirebaseID",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#getFirebaseID",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#gethours",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-getHours",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#getHours",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#getophours",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-getOpHours",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#getOpHours",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#getpois",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-getPOIS",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#getPOIS",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#getqueue",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-getQueue",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#getQueue",
    "method"
  ],
  [
    "lib/parks/europapark/europaparkbase.js~europaparkbase#loginep",
    "class/lib/parks/europapark/europaparkbase.js~EuropaParkBase.html#instance-method-loginEP",
    "lib/parks/europapark/europaparkbase.js~EuropaParkBase#loginEP",
    "method"
  ],
  [
    "lib/parks/europapark/rulantica.js",
    "file/lib/parks/europapark/rulantica.js.html",
    "lib/parks/europapark/rulantica.js",
    "file"
  ],
  [
    "lib/parks/europapark/rulantica.js~rulantica#constructor",
    "class/lib/parks/europapark/rulantica.js~Rulantica.html#instance-constructor-constructor",
    "lib/parks/europapark/rulantica.js~Rulantica#constructor",
    "method"
  ],
  [
    "lib/parks/europapark/yullbe.js",
    "file/lib/parks/europapark/yullbe.js.html",
    "lib/parks/europapark/yullbe.js",
    "file"
  ],
  [
    "lib/parks/europapark/yullbe.js~yullbe#constructor",
    "class/lib/parks/europapark/yullbe.js~Yullbe.html#instance-constructor-constructor",
    "lib/parks/europapark/yullbe.js~Yullbe#constructor",
    "method"
  ],
  [
    "lib/parks/location.js",
    "file/lib/parks/location.js.html",
    "lib/parks/location.js",
    "file"
  ],
  [
    "lib/parks/location.js~location.randombetween",
    "class/lib/parks/location.js~Location.html#static-method-randomBetween",
    "lib/parks/location.js~Location.randomBetween",
    "method"
  ],
  [
    "lib/parks/park.js",
    "file/lib/parks/park.js.html",
    "lib/parks/park.js",
    "file"
  ],
  [
    "lib/parks/park.js~park#cache",
    "class/lib/parks/park.js~Park.html#instance-member-cache",
    "lib/parks/park.js~Park#cache",
    "member"
  ],
  [
    "lib/parks/park.js~park#constructor",
    "class/lib/parks/park.js~Park.html#instance-constructor-constructor",
    "lib/parks/park.js~Park#constructor",
    "method"
  ],
  [
    "lib/parks/park.js~park#getcalendar",
    "class/lib/parks/park.js~Park.html#instance-method-getCalendar",
    "lib/parks/park.js~Park#getCalendar",
    "method"
  ],
  [
    "lib/parks/park.js~park#getdata",
    "class/lib/parks/park.js~Park.html#instance-method-getData",
    "lib/parks/park.js~Park#getData",
    "method"
  ],
  [
    "lib/parks/park.js~park#getfairytale",
    "class/lib/parks/park.js~Park.html#instance-method-getFairytale",
    "lib/parks/park.js~Park#getFairytale",
    "method"
  ],
  [
    "lib/parks/park.js~park#gethalloween",
    "class/lib/parks/park.js~Park.html#instance-method-getHalloween",
    "lib/parks/park.js~Park#getHalloween",
    "method"
  ],
  [
    "lib/parks/park.js~park#getmerchandise",
    "class/lib/parks/park.js~Park.html#instance-method-getMerchandise",
    "lib/parks/park.js~Park#getMerchandise",
    "method"
  ],
  [
    "lib/parks/park.js~park#getpark",
    "class/lib/parks/park.js~Park.html#instance-method-getPark",
    "lib/parks/park.js~Park#getPark",
    "method"
  ],
  [
    "lib/parks/park.js~park#getrestaurant",
    "class/lib/parks/park.js~Park.html#instance-method-getRestaurant",
    "lib/parks/park.js~Park#getRestaurant",
    "method"
  ],
  [
    "lib/parks/park.js~park#getrides",
    "class/lib/parks/park.js~Park.html#instance-method-getRides",
    "lib/parks/park.js~Park#getRides",
    "method"
  ],
  [
    "lib/parks/park.js~park#getservice",
    "class/lib/parks/park.js~Park.html#instance-method-getService",
    "lib/parks/park.js~Park#getService",
    "method"
  ],
  [
    "lib/parks/park.js~park#getshows",
    "class/lib/parks/park.js~Park.html#instance-method-getShows",
    "lib/parks/park.js~Park#getShows",
    "method"
  ],
  [
    "lib/parks/park.js~park#getstatic",
    "class/lib/parks/park.js~Park.html#instance-method-getStatic",
    "lib/parks/park.js~Park#getStatic",
    "method"
  ],
  [
    "lib/parks/park.js~park#getwaittime",
    "class/lib/parks/park.js~Park.html#instance-method-getWaitTime",
    "lib/parks/park.js~Park#getWaitTime",
    "method"
  ],
  [
    "lib/parks/park.js~park#getwaittimes",
    "class/lib/parks/park.js~Park.html#instance-method-getWaitTimes",
    "lib/parks/park.js~Park#getWaitTimes",
    "method"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js",
    "file/lib/parks/phantasialand/phantasialand.js.html",
    "lib/parks/phantasialand/phantasialand.js",
    "file"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js~phantasialand#buildeventpoi",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html#instance-method-buildEventPOI",
    "lib/parks/phantasialand/phantasialand.js~Phantasialand#buildEventPOI",
    "method"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js~phantasialand#buildhotelbarpoi",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html#instance-method-buildHotelBarPOI",
    "lib/parks/phantasialand/phantasialand.js~Phantasialand#buildHotelBarPOI",
    "method"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js~phantasialand#buildhotelpoi",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html#instance-method-buildHotelPOI",
    "lib/parks/phantasialand/phantasialand.js~Phantasialand#buildHotelPOI",
    "method"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js~phantasialand#buildmerchandisepoi",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html#instance-method-buildMerchandisePOI",
    "lib/parks/phantasialand/phantasialand.js~Phantasialand#buildMerchandisePOI",
    "method"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js~phantasialand#buildrestaurantpoi",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html#instance-method-buildRestaurantPOI",
    "lib/parks/phantasialand/phantasialand.js~Phantasialand#buildRestaurantPOI",
    "method"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js~phantasialand#buildridepoi",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html#instance-method-buildRidePOI",
    "lib/parks/phantasialand/phantasialand.js~Phantasialand#buildRidePOI",
    "method"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js~phantasialand#buildservicepoi",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html#instance-method-buildServicePOI",
    "lib/parks/phantasialand/phantasialand.js~Phantasialand#buildServicePOI",
    "method"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js~phantasialand#constructor",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html#instance-constructor-constructor",
    "lib/parks/phantasialand/phantasialand.js~Phantasialand#constructor",
    "method"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js~phantasialand#getpois",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html#instance-method-getPOIS",
    "lib/parks/phantasialand/phantasialand.js~Phantasialand#getPOIS",
    "method"
  ],
  [
    "lib/parks/phantasialand/phantasialand.js~phantasialand#getwaittime",
    "class/lib/parks/phantasialand/phantasialand.js~Phantasialand.html#instance-method-getWaitTime",
    "lib/parks/phantasialand/phantasialand.js~Phantasialand#getWaitTime",
    "method"
  ],
  [
    "lib/parks/tags.js",
    "file/lib/parks/tags.js.html",
    "lib/parks/tags.js",
    "file"
  ],
  [
    "lib/parks/toverland/toverland.js",
    "file/lib/parks/toverland/toverland.js.html",
    "lib/parks/toverland/toverland.js",
    "file"
  ],
  [
    "lib/parks/toverland/toverland.js~toverland#buildhalloweenpoi",
    "class/lib/parks/toverland/toverland.js~Toverland.html#instance-method-buildHalloweenPOI",
    "lib/parks/toverland/toverland.js~Toverland#buildHalloweenPOI",
    "method"
  ],
  [
    "lib/parks/toverland/toverland.js~toverland#buildmerchandisepoi",
    "class/lib/parks/toverland/toverland.js~Toverland.html#instance-method-buildMerchandisePOI",
    "lib/parks/toverland/toverland.js~Toverland#buildMerchandisePOI",
    "method"
  ],
  [
    "lib/parks/toverland/toverland.js~toverland#buildrestaurantpoi",
    "class/lib/parks/toverland/toverland.js~Toverland.html#instance-method-buildRestaurantPOI",
    "lib/parks/toverland/toverland.js~Toverland#buildRestaurantPOI",
    "method"
  ],
  [
    "lib/parks/toverland/toverland.js~toverland#buildridepoi",
    "class/lib/parks/toverland/toverland.js~Toverland.html#instance-method-buildRidePOI",
    "lib/parks/toverland/toverland.js~Toverland#buildRidePOI",
    "method"
  ],
  [
    "lib/parks/toverland/toverland.js~toverland#buildservicepoi",
    "class/lib/parks/toverland/toverland.js~Toverland.html#instance-method-buildServicePOI",
    "lib/parks/toverland/toverland.js~Toverland#buildServicePOI",
    "method"
  ],
  [
    "lib/parks/toverland/toverland.js~toverland#buildshowpoi",
    "class/lib/parks/toverland/toverland.js~Toverland.html#instance-method-buildShowPOI",
    "lib/parks/toverland/toverland.js~Toverland#buildShowPOI",
    "method"
  ],
  [
    "lib/parks/toverland/toverland.js~toverland#constructor",
    "class/lib/parks/toverland/toverland.js~Toverland.html#instance-constructor-constructor",
    "lib/parks/toverland/toverland.js~Toverland#constructor",
    "method"
  ],
  [
    "lib/parks/toverland/toverland.js~toverland#getophours",
    "class/lib/parks/toverland/toverland.js~Toverland.html#instance-method-getOpHours",
    "lib/parks/toverland/toverland.js~Toverland#getOpHours",
    "method"
  ],
  [
    "lib/parks/toverland/toverland.js~toverland#getqueue",
    "class/lib/parks/toverland/toverland.js~Toverland.html#instance-method-getQueue",
    "lib/parks/toverland/toverland.js~Toverland#getQueue",
    "method"
  ],
  [
    "lib/parks/types.js",
    "file/lib/parks/types.js.html",
    "lib/parks/types.js",
    "file"
  ],
  [
    "lib/parks/walibi/walibibelgium.js",
    "file/lib/parks/walibi/walibibelgium.js.html",
    "lib/parks/walibi/walibibelgium.js",
    "file"
  ],
  [
    "lib/parks/walibi/walibibelgium.js~walibibelgium#constructor",
    "class/lib/parks/walibi/walibibelgium.js~WalibiBelgium.html#instance-constructor-constructor",
    "lib/parks/walibi/walibibelgium.js~WalibiBelgium#constructor",
    "method"
  ],
  [
    "lib/parks/walibi/walibiholland.js",
    "file/lib/parks/walibi/walibiholland.js.html",
    "lib/parks/walibi/walibiholland.js",
    "file"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#constructor",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-constructor-constructor",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#constructor",
    "method"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#getophours",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-method-getOpHours",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#getOpHours",
    "method"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#getqueue",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-method-getQueue",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#getQueue",
    "method"
  ],
  [
    "lib/parks/walibi/walibira.js",
    "file/lib/parks/walibi/walibira.js.html",
    "lib/parks/walibi/walibira.js",
    "file"
  ],
  [
    "lib/parks/walibi/walibira.js~walibira#constructor",
    "class/lib/parks/walibi/walibira.js~WalibiRA.html#instance-constructor-constructor",
    "lib/parks/walibi/walibira.js~WalibiRA#constructor",
    "method"
  ],
  [
    "lib/reusepromises.js",
    "file/lib/reusePromises.js.html",
    "lib/reusePromises.js",
    "file"
  ]
]