window.esdocSearchIndex = [
  [
    "@alexvv13/tpapi/lib/parks/efteling/efteling.js~efteling",
    "class/lib/parks/efteling/efteling.js~Efteling.html",
    "<span>Efteling</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/efteling/efteling.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/europapark/europapark.js~europapark",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html",
    "<span>EuropaPark</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/europapark/europapark.js</span>",
    "class"
  ],
  [
    "@alexvv13/tpapi/lib/parks/walibi/walibiholland.js~walibiholland",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html",
    "<span>WalibiHolland</span> <span class=\"search-result-import-path\">@alexvv13/tpapi/lib/parks/walibi/walibiholland.js</span>",
    "class"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/parks/efteling/efteling.js",
    "file/lib/parks/efteling/efteling.js.html",
    "lib/parks/efteling/efteling.js",
    "file"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#apikey",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-member-apiKey",
    "lib/parks/efteling/efteling.js~Efteling#apiKey",
    "member"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#constructor",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-constructor-constructor",
    "lib/parks/efteling/efteling.js~Efteling#constructor",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getcalendar",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getCalendar",
    "lib/parks/efteling/efteling.js~Efteling#getCalendar",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getdata",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getData",
    "lib/parks/efteling/efteling.js~Efteling#getData",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getophours",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getOpHours",
    "lib/parks/efteling/efteling.js~Efteling#getOpHours",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getpois",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getPOIS",
    "lib/parks/efteling/efteling.js~Efteling#getPOIS",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getqueue",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getQueue",
    "lib/parks/efteling/efteling.js~Efteling#getQueue",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#getwaittime",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-method-getWaitTime",
    "lib/parks/efteling/efteling.js~Efteling#getWaitTime",
    "method"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#histurl",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-member-histURL",
    "lib/parks/efteling/efteling.js~Efteling#histURL",
    "member"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#langoptions",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-member-langoptions",
    "lib/parks/efteling/efteling.js~Efteling#langoptions",
    "member"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#languages",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-member-languages",
    "lib/parks/efteling/efteling.js~Efteling#languages",
    "member"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#latitude",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-member-latitude",
    "lib/parks/efteling/efteling.js~Efteling#latitude",
    "member"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#longitude",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-member-longitude",
    "lib/parks/efteling/efteling.js~Efteling#longitude",
    "member"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#name",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-member-name",
    "lib/parks/efteling/efteling.js~Efteling#name",
    "member"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#searchurl",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-member-searchURL",
    "lib/parks/efteling/efteling.js~Efteling#searchURL",
    "member"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#timezone",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-member-timezone",
    "lib/parks/efteling/efteling.js~Efteling#timezone",
    "member"
  ],
  [
    "lib/parks/efteling/efteling.js~efteling#waittimesurl",
    "class/lib/parks/efteling/efteling.js~Efteling.html#instance-member-waitTimesURL",
    "lib/parks/efteling/efteling.js~Efteling#waitTimesURL",
    "member"
  ],
  [
    "lib/parks/europapark/europapark.js",
    "file/lib/parks/europapark/europapark.js.html",
    "lib/parks/europapark/europapark.js",
    "file"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#apibase",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-member-apiBase",
    "lib/parks/europapark/europapark.js~EuropaPark#apiBase",
    "member"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#constructor",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-constructor-constructor",
    "lib/parks/europapark/europapark.js~EuropaPark#constructor",
    "method"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#getcalendar",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-method-getCalendar",
    "lib/parks/europapark/europapark.js~EuropaPark#getCalendar",
    "method"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#getdata",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-method-getData",
    "lib/parks/europapark/europapark.js~EuropaPark#getData",
    "method"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#getophours",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-method-getOpHours",
    "lib/parks/europapark/europapark.js~EuropaPark#getOpHours",
    "method"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#getpois",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-method-getPOIS",
    "lib/parks/europapark/europapark.js~EuropaPark#getPOIS",
    "method"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#getqueue",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-method-getQueue",
    "lib/parks/europapark/europapark.js~EuropaPark#getQueue",
    "method"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#getwaittime",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-method-getWaitTime",
    "lib/parks/europapark/europapark.js~EuropaPark#getWaitTime",
    "method"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#langoptions",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-member-langoptions",
    "lib/parks/europapark/europapark.js~EuropaPark#langoptions",
    "member"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#languages",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-member-languages",
    "lib/parks/europapark/europapark.js~EuropaPark#languages",
    "member"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#latitude",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-member-latitude",
    "lib/parks/europapark/europapark.js~EuropaPark#latitude",
    "member"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#login",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-member-login",
    "lib/parks/europapark/europapark.js~EuropaPark#login",
    "member"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#loginep",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-method-loginEP",
    "lib/parks/europapark/europapark.js~EuropaPark#loginEP",
    "method"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#loginurl",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-member-loginurl",
    "lib/parks/europapark/europapark.js~EuropaPark#loginurl",
    "member"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#longitude",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-member-longitude",
    "lib/parks/europapark/europapark.js~EuropaPark#longitude",
    "member"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#name",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-member-name",
    "lib/parks/europapark/europapark.js~EuropaPark#name",
    "member"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#refresh",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-member-refresh",
    "lib/parks/europapark/europapark.js~EuropaPark#refresh",
    "member"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#refreshep",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-method-refreshEP",
    "lib/parks/europapark/europapark.js~EuropaPark#refreshEP",
    "method"
  ],
  [
    "lib/parks/europapark/europapark.js~europapark#timezone",
    "class/lib/parks/europapark/europapark.js~EuropaPark.html#instance-member-timezone",
    "lib/parks/europapark/europapark.js~EuropaPark#timezone",
    "member"
  ],
  [
    "lib/parks/index.js",
    "file/lib/parks/index.js.html",
    "lib/parks/index.js",
    "file"
  ],
  [
    "lib/parks/walibi/walibiholland.js",
    "file/lib/parks/walibi/walibiholland.js.html",
    "lib/parks/walibi/walibiholland.js",
    "file"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#apibase",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-member-apiBase",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#apiBase",
    "member"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#apiurl",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-member-apiUrl",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#apiUrl",
    "member"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#constructor",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-constructor-constructor",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#constructor",
    "method"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#getcalendar",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-method-getCalendar",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#getCalendar",
    "method"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#getdata",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-method-getData",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#getData",
    "method"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#getophours",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-method-getOpHours",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#getOpHours",
    "method"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#getpois",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-method-getPOIS",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#getPOIS",
    "method"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#getwaittime",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-method-getWaitTime",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#getWaitTime",
    "method"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#langoptions",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-member-langoptions",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#langoptions",
    "member"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#languages",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-member-languages",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#languages",
    "member"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#latitude",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-member-latitude",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#latitude",
    "member"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#longitude",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-member-longitude",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#longitude",
    "member"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#name",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-member-name",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#name",
    "member"
  ],
  [
    "lib/parks/walibi/walibiholland.js~walibiholland#timezone",
    "class/lib/parks/walibi/walibiholland.js~WalibiHolland.html#instance-member-timezone",
    "lib/parks/walibi/walibiholland.js~WalibiHolland#timezone",
    "member"
  ]
]